# - name: Template linux preseed file
#   template:
#     src: preseed.cfg.j2
#     dest: ./http/preseed.cfg

# - name: Template provisionning script part 1
#   template:
#     src: ubuntu_ovf_setup_1.sh.j2
#     dest: ./scripts/ubuntu_ovf_setup_1.sh

# - name: Template provisionning script part 2
#   template:
#     src: ubuntu_ovf_setup_2.sh.j2
#     dest: ./scripts/ubuntu_ovf_setup_2.sh

# - name: Template Packer json config
#   template:
#     src: ubuntu_iso_to_ovf.json.j2
#     dest: ./ubuntu_iso_to_ovf.json

# - name: Template Packer json config
#   template:
#     src: ubuntu_ovf_to_ovf.json.j2
#     dest: ./ubuntu_ovf_to_ovf.json

- name: Template Packer json config
  template:
    src: ubuntu_lxd.json.j2
    dest: ./ubuntu_lxd.json
